apiVersion: apps/v1
kind: Deployment
metadata:
  name: omni-esm2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-api
  template:
    metadata:
      labels:
        app: model-api
    spec:
      containers:
        - name: model-api
          image: tylermaran/omni-esm2:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "1Gi"
              cpu: "500m"
